# -*- coding: utf-8 -*-
"""Fifa Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tll_JFErNK1HIbAaKFN4YS-eILIz4ghT
"""

import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import pandas as pd

fifa = pd.read_csv("https://raw.githubusercontent.com/Pradyumn10/Data-Science-Python/master/Data%20Analysis/Fifa%20Analysis/fifa%20data.csv")

fifa.head()

for col in fifa.columns:
  print(col)

fifa.shape

nationality=fifa['nationality'].value_counts()

nationality[0:10]

nationality[0:5].keys()

plt.figure(figsize=(5,5))
plt.bar(list(nationality[0:5].keys()),list(nationality[0:5]),color="b")
plt.show()

player_salary = fifa[['short_name','wage_eur']]

player_salary.head()

plt.figure(figsize=(8,5))
plt.bar(list(player_salary['short_name'])[0:5],list(player_salary['wage_eur'])[0:5],color=["blue","green","red","pink","orange"])
plt.show()

fifa['nationality']=='Germany'

#Germany
Germany=fifa[fifa['nationality']=='Germany']
Germany.head(10)

Germany.sort_values(by=['height_cm'],ascending=False).head()

Germany.sort_values(by=['weight_kg'],ascending=False).head()

Germany.sort_values(by=['wage_eur'],ascending=False).head()

Germany[['short_name','wage_eur']].sort_values(by=['wage_eur'],ascending=False).head()

#Shooting
player_shooting= fifa[['short_name','shooting']]

player_shooting.sort_values(by=['shooting'],ascending=False).head()

#defending
player_defending= fifa[['short_name','defending','nationality','club']]

player_defending.sort_values(by=['defending'],ascending=False).head()

real_madrid=fifa[fifa['club']=='Real Madrid']

real_madrid.sort_values(by=['wage_eur'],ascending=False).head()

real_madrid.sort_values(by=['defending'],ascending=False).head()

real_madrid['nationality'].value_counts()

